name: PR Filter Demo

on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/**.js'

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR details
        run: |
          echo "This workflow ran because:"
          echo "1. A pull request is targeting main"
          echo "2. JavaScript files in src/ were modified"